cShareSystems.load_pas("eXodus 1v1", [
	"coui://ui/mods/maps/systems/amazonassafari.pas",
	"coui://ui/mods/maps/systems/aquarius.pas",
	"coui://ui/mods/maps/systems/arctic.pas",
	"coui://ui/mods/maps/systems/atlantis.pas",
	"coui://ui/mods/maps/systems/berg.pas",
	"coui://ui/mods/maps/systems/blitz.pas",
	"coui://ui/mods/maps/systems/boading.pas",
	"coui://ui/mods/maps/systems/cauldron.pas",
	"coui://ui/mods/maps/systems/chess.pas",
	"coui://ui/mods/maps/systems/chlorophyte.pas",
	"coui://ui/mods/maps/systems/chocke.pas",
	"coui://ui/mods/maps/systems/closair.pas",
	"coui://ui/mods/maps/systems/clutch_of annihilation.pas",
	"coui://ui/mods/maps/systems/coldfeets.pas",
	"coui://ui/mods/maps/systems/coruscant.pas",
	"coui://ui/mods/maps/systems/cratered.pas",
	"coui://ui/mods/maps/systems/derisia.pas",
	"coui://ui/mods/maps/systems/diadem.pas",
	"coui://ui/mods/maps/systems/dorne_system.pas",
	"coui://ui/mods/maps/systems/duat.pas",
	"coui://ui/mods/maps/systems/desert.pas",
	"coui://ui/mods/maps/systems/elijahs_path shared.pas",
	"coui://ui/mods/maps/systems/farenheit.pas",
	"coui://ui/mods/maps/systems/finns_revenge.pas",
	"coui://ui/mods/maps/systems/fortress.pas",
	"coui://ui/mods/maps/systems/frozen.pas",
	"coui://ui/mods/maps/systems/frozenoreoyoghurt.pas",
	"coui://ui/mods/maps/systems/gsystem.pas",
	"coui://ui/mods/maps/systems/hades.pas",
	"coui://ui/mods/maps/systems/ignus.pas",
	"coui://ui/mods/maps/systems/incontrovertible.pas",
	"coui://ui/mods/maps/systems/kimberlee_1v1.pas",
	"coui://ui/mods/maps/systems/kinomo.pas",
	"coui://ui/mods/maps/systems/lazona.pas",
	"coui://ui/mods/maps/systems/living_forge.pas",
	"coui://ui/mods/maps/systems/lockery.pas",
	"coui://ui/mods/maps/systems/lugaan.pas",
	"coui://ui/mods/maps/systems/lush.pas",
	"coui://ui/mods/maps/systems/molten.pas",
	"coui://ui/mods/maps/systems/moore.pas",
	"coui://ui/mods/maps/systems/oblivarum.pas",
	"coui://ui/mods/maps/systems/omega.pas",
	"coui://ui/mods/maps/systems/outlier.pas",
	"coui://ui/mods/maps/systems/overcookedpizza.pas",
	"coui://ui/mods/maps/systems/pressure_cooker.pas",
	"coui://ui/mods/maps/systems/prof_x.pas",
	"coui://ui/mods/maps/systems/roc.pas",
	"coui://ui/mods/maps/systems/sauron.pas",
	"coui://ui/mods/maps/systems/semmo.pas",
	"coui://ui/mods/maps/systems/sinnet.pas",
	"coui://ui/mods/maps/systems/soliture.pas",
	"coui://ui/mods/maps/systems/smelter.pas",
	"coui://ui/mods/maps/systems/t-_crevage.pas",
	"coui://ui/mods/maps/systems/t-_geyser.pas",
	"coui://ui/mods/maps/systems/t-_harbour.pas",
	"coui://ui/mods/maps/systems/t-_hydrogenix facility f407.pas",
	"coui://ui/mods/maps/systems/t-_insanateria.pas",
	"coui://ui/mods/maps/systems/t-_kure atoll.pas",
	"coui://ui/mods/maps/systems/t-_the island.pas",
	"coui://ui/mods/maps/systems/tectonic.pas",
	"coui://ui/mods/maps/systems/theclassybarren.pas",
	"coui://ui/mods/maps/systems/thermopylae.pas",
	"coui://ui/mods/maps/systems/thewall.pas",
	"coui://ui/mods/maps/systems/thief's_pass.pas",
	"coui://ui/mods/maps/systems/the_faceoff.pas",
	"coui://ui/mods/maps/systems/the_forgery.pas",
	"coui://ui/mods/maps/systems/the_reef.pas",
	"coui://ui/mods/maps/systems/toisengard.pas",
	"coui://ui/mods/maps/systems/tundra.pas",
	"coui://ui/mods/maps/systems/venetzia.pas",
	"coui://ui/mods/maps/systems/zetox.pas"
]);
cShareSystems.load_pas("eXodus 2v2", [
	"coui://ui/mods/maps/systems/atlantis.pas",
	"coui://ui/mods/maps/systems/deathstar.pas",
	"coui://ui/mods/maps/systems/duel_lake.pas",
	"coui://ui/mods/maps/systems/fields_of_isis.pas",
	"coui://ui/mods/maps/systems/frozenoreoyoghurt.pas",
	"coui://ui/mods/maps/systems/gsystem_vs2v2.pas",
	"coui://ui/mods/maps/systems/icy_v17.pas",
	"coui://ui/mods/maps/systems/incontrovertible.pas",
	"coui://ui/mods/maps/systems/kinetics_multi_4v.pas",
	"coui://ui/mods/maps/systems/lockery.pas",
	"coui://ui/mods/maps/systems/seton's_grip.pas",
	"coui://ui/mods/maps/systems/the_t3mple_v2.pas",
	"coui://ui/mods/maps/systems/elrose_v18.pas",
	"coui://ui/mods/maps/systems/t-_kure atoll.pas",
	"coui://ui/mods/maps/systems/tandem.pas",
	"coui://ui/mods/maps/systems/the_forgery.pas",
	"coui://ui/mods/maps/systems/the_t3mple_v2.pas",
	"coui://ui/mods/maps/systems/trials.pas",
	"coui://ui/mods/maps/systems/tropicanhoneydonut.pas",
	"coui://ui/mods/maps/systems/zetox.pas"
]);
cShareSystems.load_pas("eXodus 3v3+", [
	"coui://ui/mods/maps/systems/bang_battle.pas",
	"coui://ui/mods/maps/systems/burnt_playground.pas",
	"coui://ui/mods/maps/systems/frontlines_sa.pas",
	"coui://ui/mods/maps/systems/marshalls_lament_titans.pas",
	"coui://ui/mods/maps/systems/medea.pas",
	"coui://ui/mods/maps/systems/mots_recipe_for_disaster.pas",
	"coui://ui/mods/maps/systems/omega_belt.pas",
	"coui://ui/mods/maps/systems/seton's_grip.pas",
	"coui://ui/mods/maps/systems/t-_rain_system.pas",
	"coui://ui/mods/maps/systems/twbaby.pas",
	"coui://ui/mods/maps/systems/war_of the worlds.pas",
	"coui://ui/mods/maps/systems/worlds_collide.pas"
]);
cShareSystems.load_pas("eXodus FFA", [
	"coui://ui/mods/maps/systems/newzealandsbaby.pas",
	"coui://ui/mods/maps/systems/pockets.pas",
	"coui://ui/mods/maps/systems/the_somme.pas"
]);
