cShareSystems.load_pas("Supercommander Legion", [
	"coui://ui/mods/supercommander/systems/aquarius.pas",
	"coui://ui/mods/supercommander/systems/arctic.pas",
	"coui://ui/mods/supercommander/systems/berg.pas",
	"coui://ui/mods/supercommander/systems/boading.pas",
	"coui://ui/mods/supercommander/systems/cauldron.pas",
	"coui://ui/mods/supercommander/systems/chess.pas",
	"coui://ui/mods/supercommander/systems/chlorophyte.pas",
	"coui://ui/mods/supercommander/systems/closair.pas",
	"coui://ui/mods/supercommander/systems/clutch_of annihilation.pas",
	"coui://ui/mods/supercommander/systems/coruscant.pas",
	"coui://ui/mods/supercommander/systems/cratered.pas",
	"coui://ui/mods/supercommander/systems/derisia.pas",
	"coui://ui/mods/supercommander/systems/diadem.pas",
	"coui://ui/mods/supercommander/systems/dorne_system.pas",
	"coui://ui/mods/supercommander/systems/duat.pas",
	"coui://ui/mods/supercommander/systems/duel_lake.pas",
	"coui://ui/mods/supercommander/systems/elijahs_path shared.pas",
	"coui://ui/mods/supercommander/systems/farenheit.pas",
	"coui://ui/mods/supercommander/systems/fortress.pas",
	"coui://ui/mods/supercommander/systems/frozen.pas",
	"coui://ui/mods/supercommander/systems/ignus.pas",
	"coui://ui/mods/supercommander/systems/incontrovertible.pas",
	"coui://ui/mods/supercommander/systems/kimberlee_1v1.pas",
	"coui://ui/mods/supercommander/systems/lana's_denial.pas",
	"coui://ui/mods/supercommander/systems/lazona.pas",
	"coui://ui/mods/supercommander/systems/living_forge.pas",
	"coui://ui/mods/supercommander/systems/lockery.pas",
	"coui://ui/mods/supercommander/systems/lugaan.pas",
	"coui://ui/mods/supercommander/systems/lush.pas",
	"coui://ui/mods/supercommander/systems/molten.pas",
	"coui://ui/mods/supercommander/systems/moore.pas",
	"coui://ui/mods/supercommander/systems/oblivarum.pas",
	"coui://ui/mods/supercommander/systems/omega.pas",
	"coui://ui/mods/supercommander/systems/prof_x.pas",
	"coui://ui/mods/supercommander/systems/roc.pas",
	"coui://ui/mods/supercommander/systems/sauron.pas",
	"coui://ui/mods/supercommander/systems/semmo.pas",
	"coui://ui/mods/supercommander/systems/sinnet.pas",
	"coui://ui/mods/supercommander/systems/smelter.pas",
	"coui://ui/mods/supercommander/systems/t-_crevage.pas",
	"coui://ui/mods/supercommander/systems/t-_geyser.pas",
	"coui://ui/mods/supercommander/systems/t-_harbour.pas",
	"coui://ui/mods/supercommander/systems/t-_hydrogenix facility f407.pas",
	"coui://ui/mods/supercommander/systems/t-_insanateria.pas",
	"coui://ui/mods/supercommander/systems/t-_kure atoll.pas",
	"coui://ui/mods/supercommander/systems/t-_the island.pas",
	"coui://ui/mods/supercommander/systems/tectonic.pas",
	"coui://ui/mods/supercommander/systems/the_reef.pas",
	"coui://ui/mods/supercommander/systems/thermopylae.pas",
	"coui://ui/mods/supercommander/systems/trials.pas",	
	"coui://ui/mods/supercommander/systems/zetox.pas"		
]);